### ISSUE TITLE
Usage of before hook in test files 

### ISSUE THREAD

**Issue by ozovalihasan** [applandinc/appmap-ruby#100]
I am using RSpec for tests and used appmap for [this test file](https://github.com/ozovalihasan/track-api/blob/3dd253fbe419bdceaf7256f57ec24560fdaaaafc/spec/requests/piece_request_spec.rb).

As you can see, I am using before hook for my tests. So, empty diagrams are generated because of before hook.

If I updated [my tests by removing before hook](https://github.com/ozovalihasan/track-api/blob/fbe6521ce5c752d08a7e91382cd6e3f92c7a1f17/spec/requests/piece_request_spec.rb), diagrams are generated correctly.

Is it possible to fix this issue? Or, can a warning about usage of before hook be added to readme file?

**Comment by kgilpin** [comment]
Hi, sorry about the delay in my reply. By design, appmap-ruby doesn't record before or after hooks, because there is often a lot of work being done in these hooks that would be repeated over and over in the AppMaps. Then the AppMaps become almost undifferentiated, redundant, and hard to interpret. 

I suppose it's a matter of style for request specs, whether the request is made in a hook or in the body. But for usage with AppMap, making the request in the test body is needed if you want to see the request processing in the AppMap.
