### ISSUE TITLE
When running with Minitest, raises wrong number of arguments (given 2, expected 3)

### ISSUE THREAD

**Issue by TAGraves** [applandinc/appmap-ruby#115]
It looks like [this change](https://github.com/applandinc/appmap-ruby/pull/109) broke things for Minitest. The `save` method [takes 3 position args](https://github.com/applandinc/appmap-ruby/blob/master/lib/appmap/minitest.rb#L81), but [here it is called with only two](https://github.com/applandinc/appmap-ruby/blob/10eb2a5ce49634a3a479e0d9c1737b050911e473/lib/appmap/minitest.rb#L109).

**Comment by dustinbyrne** [comment]
Thanks for the report @TAGraves! We'll look in to this for an upcoming release.

**Comment by kgilpin** [comment]
Hi @TAGraves , another thing about this issue is that it's related to an outdated file called Inventory.appmap.json, which I'm actually in the process of removing. This is a branch where that file is no longer written, so it should fix your issue, if you want to give it a try - https://github.com/applandinc/appmap-ruby/pull/114/files

This will be merged & released soon.

**Comment by kgilpin** [comment]
@TAGraves this is fixed in the new release, give it a try!
