### ISSUE TITLE
Random classes included in a map 

### ISSUE THREAD

**Issue by torchello** [applandinc/appmap-ruby#131]
Some classes were included into my Rails map without being explicitly required. My config was listing several packages from `app` folder only. I had to exclude these classes manually to reduce the "noise" in the map:
```
exclude:
- ActiveSupport::Callbacks::CallbackSequence
- ActionController::Instrumentation
- JSON::Ext::Generator
```

**Comment by kgilpin** [comment]
Hi, these classes are included in the map by default because in many cases they perform an important function that helps make the map more clear.

`ActiveSupport::Callbacks::CallbackSequence` performs `before_action` and `after_action`. Without this class, it's not clear why some events in the Trace are occurring.

`ActionController::Instrumentation` wraps all the `controller` actions. Without it, it's hard to capture the full scope of the controller. You might think that it would make sense to just map the Controller class; but in many requests, the Controller class is only part of the story. The full request is served by:

* The ApplicationController base class
* Before and after actions
* The specific Controller class
* Template rendering.

 `ActionController::Instrumentation` creates a "container" that sits above all these.

`JSON::Ext::Generator` can arguably be removed. It is nice sometimes to see where JSON parsing and generation is occurring.
