### ISSUE TITLE
(Bug?) Node modules data present

### ISSUE THREAD

**Issue by mensfeld** [applandinc/appmap-ruby#182]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for Ruby libraries using WhiteSource Diffend.io.

While reviewing the changes for this lib, I noticed, that the node modules directory is being included.

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

ref: https://rubygems.org/gems/appmap - see the last release. 10x bigger than all the previous.
ref https://my.diffend.io/gems/appmap/0.62.0/0.62.1#d2h-432957

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by kgilpin** [comment]
Hi, thanks for your note. The inclusion of `node_modules` in the gem is intentional; however I would still like to look into why the cumulative size of the directory is so large.

`node_modules` is bundled with the gem because the gem provides a Rake task called `appmap:swagger` which generates Swagger/OpenAPI (https://appland.com/videos/2021/07/31/railsconf-recap-pt-3/).

To do this, the Ruby gem wraps an NPM package called `@appland/cli` (https://github.com/applandinc/appmap-js/tree/main/packages/cli). The bulk of the swagger generation is performed in the JS package. The code in the appmap gem just exposes swagger generation in a more idiomatic way for Ruby. The JS code is packaged with the gem so that the user doesn't have to install it themselves.

**Comment by mensfeld** [comment]
Thank you. Note, that the scope of changes was never that big (as you noticed):

https://my.diffend.io/gems/appmap/0.59.0/0.61.0
https://my.diffend.io/gems/appmap/0.57.1/0.58.0
https://my.diffend.io/gems/appmap/0.54.4/0.58.0
https://my.diffend.io/gems/appmap/0.58.0/0.59.0
